import type { Job, ManifestId } from './domain';
import type { Paths } from './paths';
import { logPath, plistLabel, scriptPath } from './paths';
import type { CalendarInterval } from './schedule';

/** Machine-specific values baked into the generated files. */
export type RenderEnv = {
  manifestId: ManifestId;
  /** Directory containing the claude executable, put first on PATH. */
  claudeDir: string;
  home: string;
  paths: Paths;
};

/** Environment variable in the plist that records which manifest owns a job. */
export const MANIFEST_ENV = 'CCRON_MANIFEST';

const ULIMIT = 2147483646;

export type Rendered = { script: string; plist: string };

export function render(job: Job, env: RenderEnv): Rendered {
  return {
    script: generateScriptContent(job, env),
    plist: generatePlistContent(job, env),
  };
}

function pathEntries(env: RenderEnv): string {
  return [env.claudeDir, '/usr/local/bin', '/usr/bin', '/bin'].join(':');
}

/**
 * Generate the shell script content that launchd will execute.
 */
export function generateScriptContent(job: Job, env: RenderEnv): string {
  const claudeArgs = ['claude -p "$PROMPT"'];
  if (job.mcpConfig !== undefined) {
    claudeArgs.push(`  --mcp-config ${shellQuote(job.mcpConfig)}`);
  }

  return [
    '#!/usr/bin/env bash',
    '# Generated by ccron. Do not edit manually.',
    'set -uo pipefail',
    '',
    `export HOME=${shellQuote(env.home)}`,
    `export PATH=${shellQuote(pathEntries(env))}:"$PATH"`,
    '',
    `ulimit -n ${ULIMIT} 2>/dev/null || true`,
    '',
    // Without `|| exit`, a failed cd would run claude in launchd's /tmp.
    `cd ${shellQuote(job.cwd)} || exit 1`,
    '',
    `PROMPT=${shellQuote(job.prompt)}`,
    '',
    claudeArgs.join(' \\\n'),
    '',
  ].join('\n');
}

/**
 * Generate the launchd plist XML content.
 *
 * WorkingDirectory stays /tmp even when the job sets `cwd`. launchd performs the
 * chdir itself, and that chdir is denied for TCC-protected locations (~/Desktop,
 * ~/Documents, ...), which fails the job before the script runs. The script's own
 * `cd` handles `cwd` instead.
 */
export function generatePlistContent(job: Job, env: RenderEnv): string {
  const label = plistLabel(job.name);
  const script = scriptPath(env.paths, job.name);
  const log = logPath(env.paths, job.name);

  const calendarIntervalXml = generateCalendarIntervalXml(
    job.schedule.intervals,
  );

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${escapeXml(label)}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${escapeXml(script)}</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${escapeXml(env.home)}</string>
        <key>PATH</key>
        <string>${escapeXml(pathEntries(env))}</string>
        <key>${MANIFEST_ENV}</key>
        <string>${escapeXml(env.manifestId)}</string>
    </dict>
    <key>WorkingDirectory</key>
    <string>/tmp</string>
    <key>StartCalendarInterval</key>
${calendarIntervalXml}
    <key>StandardOutPath</key>
    <string>${escapeXml(log)}</string>
    <key>StandardErrorPath</key>
    <string>${escapeXml(log)}</string>
</dict>
</plist>
`;
}

function generateCalendarIntervalXml(intervals: CalendarInterval[]): string {
  if (intervals.length === 1) {
    return indent(calendarIntervalDict(intervals[0]!), 4);
  }

  const items = intervals.map(i => indent(calendarIntervalDict(i), 8));
  return `    <array>\n${items.join('\n')}\n    </array>`;
}

function calendarIntervalDict(interval: CalendarInterval): string {
  const entries: string[] = [];
  entries.push(`<key>Hour</key>\n<integer>${interval.Hour}</integer>`);
  entries.push(`<key>Minute</key>\n<integer>${interval.Minute}</integer>`);
  if (interval.Weekday !== undefined) {
    entries.push(`<key>Weekday</key>\n<integer>${interval.Weekday}</integer>`);
  }
  return `<dict>\n${entries.map(e => indent(e, 4)).join('\n')}\n</dict>`;
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map(line => pad + line)
    .join('\n');
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function shellQuote(str: string): string {
  return `'${str.replace(/'/g, "'\\''")}'`;
}
