import type { TaskConfig, GlobalConfig } from './config';
import type { CalendarInterval } from './schedule';
import { logPath, mcpConfigPath, plistLabel, scriptPath } from './config';
import { buildMcpConfig } from './mcp';
import { homedir } from 'os';

/**
 * Generate the shell script content that launchd will execute.
 */
export function generateScriptContent(
  task: TaskConfig,
  global: GlobalConfig,
): string {
  const home = homedir();
  const pathEntries = [
    global.claudePath,
    ...global.extraPaths,
    '/usr/local/bin',
    '/usr/bin',
    '/bin',
  ]
    .filter(Boolean)
    .join(':');

  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Generated by ccron. Do not edit manually.',
    'set -uo pipefail',
    '',
    `export HOME="${home}"`,
    `export PATH="${pathEntries}:$PATH"`,
    '',
    `ulimit -n ${global.ulimit} 2>/dev/null || true`,
    '',
    'cd /tmp',
    '',
  ];

  // Prompt handling
  if (task.prompt) {
    // Escape single quotes for bash
    const escaped = task.prompt.replace(/'/g, "'\\''");
    lines.push(`PROMPT='${escaped}'`);
  }

  lines.push('');

  // Build claude command
  const claudeArgs: string[] = ['claude -p "$PROMPT"'];

  if (task.mcp.length > 0) {
    claudeArgs.push(`  --mcp-config "${mcpConfigPath(task.name)}"`);
  }

  if (task.allowedTools.length > 0) {
    claudeArgs.push(`  --allowedTools "${task.allowedTools.join(',')}"`);
  }

  lines.push(claudeArgs.join(' \\\n'));
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate the launchd plist XML content.
 */
export function generatePlistContent(
  task: TaskConfig,
  global: GlobalConfig,
  intervals: CalendarInterval[],
): string {
  const home = homedir();
  const pathEntries = [
    global.claudePath,
    ...global.extraPaths,
    '/usr/local/bin',
    '/usr/bin',
    '/bin',
  ]
    .filter(Boolean)
    .join(':');

  const label = plistLabel(task.name);
  const script = scriptPath(task.name);
  const log = logPath(task.name);

  const calendarIntervalXml = generateCalendarIntervalXml(intervals);

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${escapeXml(label)}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${escapeXml(script)}</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${escapeXml(home)}</string>
        <key>PATH</key>
        <string>${escapeXml(pathEntries)}</string>
    </dict>
    <key>WorkingDirectory</key>
    <string>/tmp</string>
    <key>StartCalendarInterval</key>
${calendarIntervalXml}
    <key>StandardOutPath</key>
    <string>${escapeXml(log)}</string>
    <key>StandardErrorPath</key>
    <string>${escapeXml(log)}</string>
</dict>
</plist>
`;
}

function generateCalendarIntervalXml(intervals: CalendarInterval[]): string {
  if (intervals.length === 1) {
    return indent(calendarIntervalDict(intervals[0]!), 4);
  }

  const items = intervals.map(i => indent(calendarIntervalDict(i), 8));
  return `    <array>\n${items.join('\n')}\n    </array>`;
}

function calendarIntervalDict(interval: CalendarInterval): string {
  const entries: string[] = [];
  entries.push(`<key>Hour</key>\n<integer>${interval.Hour}</integer>`);
  entries.push(`<key>Minute</key>\n<integer>${interval.Minute}</integer>`);
  if (interval.Weekday !== undefined) {
    entries.push(`<key>Weekday</key>\n<integer>${interval.Weekday}</integer>`);
  }
  return `<dict>\n${entries.map(e => indent(e, 4)).join('\n')}\n</dict>`;
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map(line => pad + line)
    .join('\n');
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Generate MCP config JSON string from task's MCP presets.
 */
export function generateMcpConfigContent(presets: string[]): string {
  const config = buildMcpConfig(presets);
  return JSON.stringify(config, null, 2);
}
